
# Flags that are sent to the compiler
# Do not change these
# -ansi -pedantic -g -Iinclude
CFLAGS      = -ansi -pedantic -g -Iinclude


lab2:
	gcc $(CFLAGS) src/lab2.c src/functions.c -o bin/run

clean:
	@ rm *.o
